export const SNEAKER_LIST_REQUEST = 'SNEAKER_LIST_REQUEST';
export const SNEAKER_LIST_SUCCESS = 'SNEAKER_LIST_SUCCESS';
export const SNEAKER_LIST_FAIL = 'SNEAKER_LIST_FAIL';


export const DETAIL_LIST_REQUEST = 'DETAIL_LIST_REQUEST';
export const DETAIL_LIST_SUCCESS = 'DETAIL_LIST_SUCCESS';
export const DETAIL_LIST_FAIL = 'DETAIL_LIST_FAIL';


export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAIL = 'ADD_TO_CART_FAIL';

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const CART_SAVE_SHIPPING = 'CART_SAVE_SHIPPING';
export const CART_SAVE_PAYMENT = 'CART_SAVE_PAYMENT';
